### ISSUE TITLE
Unexpect JSON response error

### ISSUE THREAD

**Issue by adrianrodriguez-io** [VolkanSah/ChatGPT-API-Integration-in-HTML-CSS-with-JS-PHP#14]
Hi,

Thanks for working in this repo, it is very interesting. 

I have tried your code but after setting my Open AI api key in config.php and writing and submit a simple Hi prompt, it returns an error like as follows.

Uncaught (in promise) SyntaxError: Unexpected end of JSON input
    at HTMLFormElement.<anonymous> (script.js:26:37)
(anonymous) @ script.js:26

What could be the problem. 

Thanks

**Comment by VolkanSah** [comment]
sorry testet again lokks good. look for syntax error please. you make the mistake . Open consoleand show for errors. Sorry bro, but if you make a mistake by a so simple script and cant understand the error, please let it, cause you can harm yourself. It is an basic to learn! Read the Readme.md again please!
